# Generated by Django 4.1.5 on 2023-05-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Titilo', max_length=200),
            preserve_default=False,
        ),
    ]
