# Generated by Django 4.1.5 on 2023-06-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
